{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rx-enterprise-adapter.fullname" . }}
  labels:
    {{- include "rx-enterprise-adapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  rx-enterprise-cert: {{ .Values.rxEnterprise.cert | quote }}
  rx-enterprise-key: {{ .Values.rxEnterprise.privateKey | quote }}
  {{- range $i, $client := .Values.clients }}
  client-{{ $i }}-secret: {{ $client.secret | quote }}
  {{- end }}
{{- end }}
